### ISSUE TITLE
Support data access via HTTPS

### ISSUE THREAD

**Issue by madflojo** [madflojo/hord#6]
**Describe the solution you'd like**
It would be nice to be able to query Hord via REST calls as there may be cases where gRPC doesn’t fit with the clients needs.

**Additional context**

Ideally a HTTP requests should map as

* Get > Get
* Post > Set
* Put > Set
* Delete > Delete

The controls type should also be JSON.

**Comment by msarajam** [comment]
I'm on it

**Comment by madflojo** [comment]
@msarajam nice! Now first question. fasthttp or net/http?

Fasthttp is of course, Fast... but Net/HTTP at-least supports HTTP/2

**Comment by madflojo** [comment]
With #13 this is no longer valid
